# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/porter/Documents/Code/CS/Constrained Markov"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/porter/Documents/Code/CS/Constrained Markov"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/porter/Documents/Code/CS/Constrained Markov/CMakeFiles" "/Users/porter/Documents/Code/CS/Constrained Markov/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/porter/Documents/Code/CS/Constrained Markov/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Markov

# Build rule for target.
Markov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Markov
.PHONY : Markov

# fast build rule for target.
Markov/fast:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/build
.PHONY : Markov/fast

src/console.o: src/console.cpp.o

.PHONY : src/console.o

# target to build an object file
src/console.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/console.cpp.o
.PHONY : src/console.cpp.o

src/console.i: src/console.cpp.i

.PHONY : src/console.i

# target to preprocess a source file
src/console.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/console.cpp.i
.PHONY : src/console.cpp.i

src/console.s: src/console.cpp.s

.PHONY : src/console.s

# target to generate assembly for a file
src/console.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/console.cpp.s
.PHONY : src/console.cpp.s

src/constrainedmarkov.o: src/constrainedmarkov.cpp.o

.PHONY : src/constrainedmarkov.o

# target to build an object file
src/constrainedmarkov.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/constrainedmarkov.cpp.o
.PHONY : src/constrainedmarkov.cpp.o

src/constrainedmarkov.i: src/constrainedmarkov.cpp.i

.PHONY : src/constrainedmarkov.i

# target to preprocess a source file
src/constrainedmarkov.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/constrainedmarkov.cpp.i
.PHONY : src/constrainedmarkov.cpp.i

src/constrainedmarkov.s: src/constrainedmarkov.cpp.s

.PHONY : src/constrainedmarkov.s

# target to generate assembly for a file
src/constrainedmarkov.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/constrainedmarkov.cpp.s
.PHONY : src/constrainedmarkov.cpp.s

src/debug.o: src/debug.cpp.o

.PHONY : src/debug.o

# target to build an object file
src/debug.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/debug.cpp.o
.PHONY : src/debug.cpp.o

src/debug.i: src/debug.cpp.i

.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/debug.cpp.i
.PHONY : src/debug.cpp.i

src/debug.s: src/debug.cpp.s

.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/debug.cpp.s
.PHONY : src/debug.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/markov.o: src/markov.cpp.o

.PHONY : src/markov.o

# target to build an object file
src/markov.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/markov.cpp.o
.PHONY : src/markov.cpp.o

src/markov.i: src/markov.cpp.i

.PHONY : src/markov.i

# target to preprocess a source file
src/markov.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/markov.cpp.i
.PHONY : src/markov.cpp.i

src/markov.s: src/markov.cpp.s

.PHONY : src/markov.s

# target to generate assembly for a file
src/markov.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/markov.cpp.s
.PHONY : src/markov.cpp.s

src/mnemonicmarkov.o: src/mnemonicmarkov.cpp.o

.PHONY : src/mnemonicmarkov.o

# target to build an object file
src/mnemonicmarkov.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/mnemonicmarkov.cpp.o
.PHONY : src/mnemonicmarkov.cpp.o

src/mnemonicmarkov.i: src/mnemonicmarkov.cpp.i

.PHONY : src/mnemonicmarkov.i

# target to preprocess a source file
src/mnemonicmarkov.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/mnemonicmarkov.cpp.i
.PHONY : src/mnemonicmarkov.cpp.i

src/mnemonicmarkov.s: src/mnemonicmarkov.cpp.s

.PHONY : src/mnemonicmarkov.s

# target to generate assembly for a file
src/mnemonicmarkov.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/mnemonicmarkov.cpp.s
.PHONY : src/mnemonicmarkov.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/Markov.dir/build.make CMakeFiles/Markov.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Markov"
	@echo "... src/console.o"
	@echo "... src/console.i"
	@echo "... src/console.s"
	@echo "... src/constrainedmarkov.o"
	@echo "... src/constrainedmarkov.i"
	@echo "... src/constrainedmarkov.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/markov.o"
	@echo "... src/markov.i"
	@echo "... src/markov.s"
	@echo "... src/mnemonicmarkov.o"
	@echo "... src/mnemonicmarkov.i"
	@echo "... src/mnemonicmarkov.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

